name: MSVC
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Generate build scripts
        run: |
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release .. -DCLSTL_TEST=1

      - name: Build
        run: |
          cd build
          nmake
          ./clstl_test.exe
